spring.application.name=router-service
server.servlet.context-path=/router-service
server.port=8080

# ===============================
# LOGGING-UAT
# ===============================

# Keep app logs detailed
logging.level.root=INFO
logging.level.com.router=DEBUG
logging.level.org.springframework.boot.web.embedded.tomcat=INFO

# Silence framework noise
logging.level.org.springframework=ERROR
logging.level.org.springframework.web=ERROR
logging.level.org.hibernate=ERROR
logging.level.org.apache.catalina=ERROR
logging.level.sun.rmi=ERROR
logging.level.javax.management=ERROR

# File logging
logging.file.name=${catalina.base:${user.home}}/logs/RouterLog.log

logging.pattern.file=%d %p %c{1} [%t] %m%n
logging.pattern.console=%d{HH:mm:ss.SSS} %-5level %logger{36} - %msg%n
