spring.application.name=router-service
server.servlet.context-path=/router-service
server.port=8080

# ===============================
# LOGGING (UAT)
# ===============================

# Root logging level (less verbose than DEV)
logging.level.root=INFO

# Reduce framework noise
logging.level.org.springframework=ERROR
logging.level.org.springframework.web=ERROR
logging.level.org.hibernate=ERROR

# Log file location (Tomcat)
logging.file.name=${catalina.base}/logs/Router-uat.log

# Log patterns
logging.pattern.file=%d %p %c{1} [%t] %m%n
logging.pattern.console=%d{HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n
